name: 'Terraform - Production'

on:
  push:
    branches:
    - main
    paths: 
    - prod/**
  pull_request:
    branches:
    - main
    paths: 
    - prod/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./prod
      
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./prod
      
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./prod